// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdLAiX8Nc9U_8bU4v4P0FSPRgTKzvzfUA',
    appId: '1:795070369342:web:e656150083cddf5ba84b6f',
    messagingSenderId: '795070369342',
    projectId: 'myapp-814bf',
    authDomain: 'myapp-814bf.firebaseapp.com',
    storageBucket: 'myapp-814bf.appspot.com',
    measurementId: 'G-QQVS18R0SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkhnjAzB3YseDO_GddpXyAOi1zKAEza3s',
    appId: '1:795070369342:android:368ae59db4199a53a84b6f',
    messagingSenderId: '795070369342',
    projectId: 'myapp-814bf',
    storageBucket: 'myapp-814bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTNaMkFZ-lpQXiBdOJna3cvUHKIJ8P1yQ',
    appId: '1:795070369342:ios:958bceaa2b224d13a84b6f',
    messagingSenderId: '795070369342',
    projectId: 'myapp-814bf',
    storageBucket: 'myapp-814bf.appspot.com',
    iosBundleId: 'com.example.parkintech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTNaMkFZ-lpQXiBdOJna3cvUHKIJ8P1yQ',
    appId: '1:795070369342:ios:b3258d556f4af836a84b6f',
    messagingSenderId: '795070369342',
    projectId: 'myapp-814bf',
    storageBucket: 'myapp-814bf.appspot.com',
    iosBundleId: 'com.example.parkintech.RunnerTests',
  );
}
